
/****** Object:  Index [PGuidIndex]    Script Date: 2014-5-19 0:26:42 ******/
CREATE NONCLUSTERED INDEX [PGuidIndex] ON [dbo].[Abstract]
(
	[PGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [PGuidIndex]    Script Date: 2014-5-19 0:26:55 ******/
CREATE NONCLUSTERED INDEX [PGuidIndex] ON [dbo].[Author]
(
	[PGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [PGuidIndex]    Script Date: 2014-5-19 0:28:12 ******/
CREATE NONCLUSTERED INDEX [PGuidIndex] ON [dbo].[AuthorInstitute]
(
	[PGuid] ASC,
	[IGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [PGuidIndex]    Script Date: 2014-5-19 0:28:24 ******/
CREATE NONCLUSTERED INDEX [PGuidIndex] ON [dbo].[Category]
(
	[PGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [PGuidIndex]    Script Date: 2014-5-19 0:28:41 ******/
CREATE NONCLUSTERED INDEX [PGuidIndex] ON [dbo].[Citation]
(
	[PGuid] ASC,
	[RGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [PGuidIndex]    Script Date: 2014-5-19 0:29:06 ******/
CREATE NONCLUSTERED INDEX [PGuidIndex] ON [dbo].[DocumentType]
(
	[PGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [PGuidIndex]    Script Date: 2014-5-19 0:29:19 ******/
CREATE NONCLUSTERED INDEX [PGuidIndex] ON [dbo].[Fund]
(
	[PGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [PGuidIndex]    Script Date: 2014-5-19 0:29:35 ******/
CREATE NONCLUSTERED INDEX [PGuidIndex] ON [dbo].[Institute]
(
	[PGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [PGuidIndex]    Script Date: 2014-5-19 0:29:44 ******/
CREATE NONCLUSTERED INDEX [PGuidIndex] ON [dbo].[Keyword]
(
	[PGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [GuidIndex]    Script Date: 2014-5-19 0:29:54 ******/
CREATE CLUSTERED INDEX [GuidIndex] ON [dbo].[Paper]
(
	[Guid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [PGuid]    Script Date: 2014-5-19 0:30:30 ******/
CREATE NONCLUSTERED INDEX [PGuid] ON [dbo].[Reference]
(
	[PGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [PGuidIndex]    Script Date: 2014-5-19 0:30:41 ******/
CREATE NONCLUSTERED INDEX [PGuidIndex] ON [dbo].[ReprintAuthor]
(
	[PGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

